nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  getmorebrain:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true


preferInteractive: true

yarnPath: .yarn/releases/yarn-3.5.0.cjs

