nodeLinker: node-modules

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  getmorebrain:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
